export function aboutTexts() {
  const aboutTexts = {
    "home_page-title": {
      en: "Azur Life | About",
      fr: "Azur Life",
      ru: "Azur Life | О нас",
      it: "Azur Life",
    },
    "home_page-logo": {
      en: "Azur Life",
      fr: "Azur Life",
      ru: "Azur Life",
      it: "Azur Life",
    },
    "home_page-header_location": {
      en: "France, 46 Boulevard Leclerc, 06310, Beaulieu-sur-Mer",
      fr: "France, 46 Boulevard Leclerc, 06310, Beaulieu-sur-Mer",
      ru: "Франция, бульвар Леклерк, 46, 06310, Болье-сюр-Мер",
      it: "Francia, 46 Boulevard Leclerc, 06310, Beaulieu-sur-Mer",
    },
    "home_page-header_title": {
      en: "",
      fr: "",
      ru: "Сделки на русском языке с Вашей недвижимостью во Франции с 2017 года",
      it: "",
    },
    "home_page-header_text": {
      en: "",
      fr: "",
      ru: "Открываем новые горизонты Франции для Вас. Мы подберем недвижимость исходя из озвученных запросов, обеспечим управление вашими апартаментами или окажем услугу консьерж-сервиса, а вам остается только одно: наслаждаться жизнью.",
      it: "",
    },
    "home_page-header_btn-download": {
      en: "Broshure",
      fr: "Brochure",
      ru: "Скачать презентацию",
      it: "Opuscolo",
    },
    "home_page-header_btn-contact": {
      en: "Contact Us",
      fr: "Contactez-nous",
      ru: "Напишите нам",
      it: "Contattaci",
    },
    "home_page-menu_main_link_1": {
      en: "About us",
      fr: "À propos de nous",
      ru: "О нас",
      it: "Di noi",
    },
    "home_page-menu_main_link_2": {
      en: "All objects",
      fr: "Tous les objets",
      ru: "Все объекты",
      it: "Tutti gli oggetti",
    },
    "home_page-menu_main_link_3": {
      en: "Sale",
      fr: "Vente",
      ru: "Продажа",
      it: "Vendita",
    },
    "home_page-menu_main_link_4": {
      en: "Rent",
      fr: "Location",
      ru: "Аренда",
      it: "Affitto",
    },
    "home_page-menu_main_link_5": {
      en: "Blog",
      fr: "Blog",
      ru: "Блог",
      it: "Blog",
    },
    "home_page-menu_main_link_6": {
      en: "Join us",
      fr: "Rejoignez-nous",
      ru: "Присоединиться к нам",
      it: "Unisciti a noi",
    },
    "home_page-menu_main_link_7": {
      en: "Buy, sell, rent with us",
      fr: "Acheter, vendre, louer avec nous",
      ru: "Купить,  продать, арендовать с нами",
      it: "Comprare, vendere, affittare con noi",
    },
    "home_page-menu_main_link_8": {
      en: "Expert assessment",
      fr: "Avis d'expert",
      ru: "Экспертная оценка",
      it: "Revisione tra pari",
    },
    "home_page-menu_main_link_9": {
      en: "Presentation",
      fr: "Présentation",
      ru: "Презентация",
      it: "Presentazione",
    },
    "home_page-menu_service_link_1": {
      en: "Property Management",
      fr: "Gestion immobilière",
      ru: "Управление недвижимостью",
      it: "Gestione immobiliare",
    },
    "home_page-menu_service_link_2": {
      en: "Concierge service",
      fr: "Service de conciergerie",
      ru: "Консьерж-сервис",
      it: "Servizio concierge",
    },
    "home_page-menu_contact_link": {
      en: "Contact us",
      fr: "Contactez-nous",
      ru: "Связаться с нами",
      it: "Contattaci",
    },
    "home_page-menu_bottom_link_1": {
      en: "Our commission",
      fr: "Notre Commission",
      ru: "Наша комиссия",
      it: "La nostra commissione",
    },
    "home_page-menu_bottom_link_2": {
      en: "Privacy policy",
      fr: "Politique de confidentialité",
      ru: "Политика конфиденциальности",
      it: "Informativa sulla privacy",
    },
    "home_page-": {
      en: "",
      fr: "",
      ru: "",
      it: "",
    },
    "home_page-": {
      en: "",
      fr: "",
      ru: "",
      it: "",
    },
    "home_page-": {
      en: "",
      fr: "",
      ru: "",
      it: "",
    },
    "home_page-": {
      en: "",
      fr: "",
      ru: "",
      it: "",
    },
    "home_page-": {
      en: "",
      fr: "",
      ru: "",
      it: "",
    },
    "home_page-": {
      en: "",
      fr: "",
      ru: "",
      it: "",
    },
    "home_page-": {
      en: "",
      fr: "",
      ru: "",
      it: "",
    },
    "home_page-": {
      en: "",
      fr: "",
      ru: "",
      it: "",
    },
    "home_page-": {
      en: "",
      fr: "",
      ru: "",
      it: "",
    },
    "home_page-": {
      en: "",
      fr: "",
      ru: "",
      it: "",
    },
    "home_page-": {
      en: "",
      fr: "",
      ru: "",
      it: "",
    },
    "home_page-": {
      en: "",
      fr: "",
      ru: "",
      it: "",
    },
    "home_page-": {
      en: "",
      fr: "",
      ru: "",
      it: "",
    },
    "home_page-": {
      en: "",
      fr: "",
      ru: "",
      it: "",
    },
    "home_page-": {
      en: "",
      fr: "",
      ru: "",
      it: "",
    },
    "home_page-": {
      en: "",
      fr: "",
      ru: "",
      it: "",
    },
    "home_page-foter_form_title": {
      en: "Call me back",
      fr: "Rappelez-moi",
      ru: "Перезвоните мне",
      it: "Richiamami",
    },
    "home_page-foter_form_name": {
      en: "Name",
      fr: "Nom",
      ru: "Имя",
      it: "Nome",
    },
    "home_page-foter_form_tel": {
      en: "Telephone",
      fr: "Téléphone",
      ru: "Телефон",
      it: "Telefono",
    },
    "home_page-foter_form_email": {
      en: "E-mail",
      fr: "E-mail",
      ru: "Электронная почта",
      it: "E-mail",
    },

    "home_page-foter_form_btn": {
      en: "Send a request",
      fr: "Envoyer une demande",
      ru: "Отправить запрос",
      it: "Invia richiesta",
    },
    "home_page-footer_location": {
      en: "France, 46 Boulevard Leclerc, 06310, Beaulieu-sur-Mer",
      fr: "France, 46 Boulevard Leclerc, 06310, Beaulieu-sur-Mer",
      ru: "Франция, бульвар Леклерк, 46, 06310, Болье-сюр-Мер",
      it: "Francia, 46 Boulevard Leclerc, 06310, Beaulieu-sur-Mer",
    },
    "home_page-footer_nav_title": {
      en: "Navigation",
      fr: "Navigation",
      ru: "Навигация",
      it: "Navigazione",
    },
    "home_page-footer_nav_link_1": {
      en: "About us",
      fr: "À propos de nous",
      ru: "О нас",
      it: "Di noi",
    },
    "home_page-footer_nav_link_2": {
      en: "All objects",
      fr: "Tous les objets",
      ru: "Все объекты",
      it: "Tutti gli oggetti",
    },
    "home_page-footer_nav_link_3": {
      en: "Sale",
      fr: "Vente",
      ru: "Продажа",
      it: "Vendita",
    },
    "home_page-footer_nav_link_4": {
      en: "Rent",
      fr: "Location",
      ru: "Аренда",
      it: "Affitto",
    },
    "home_page-footer_nav_link_5": {
      en: "Buy, sell, rent with us",
      fr: "Acheter, vendre, louer avec nous",
      ru: "Купить,  продать, арендовать с нами",
      it: "Comprare, vendere, affittare con noi",
    },
    "home_page-footer_nav_link_6": {
      en: "Presentation",
      fr: "Présentation",
      ru: "Презентация",
      it: "Presentazione",
    },
    "home_page-footer_nav_link_7": {
      en: "Expert assessment",
      fr: "Avis d'expert",
      ru: "Экспертная оценка",
      it: "Revisione tra pari",
    },
    "home_page-footer_nav_link_8": {
      en: "Property Management",
      fr: "Gestion immobilière",
      ru: "Управление недвижимостью",
      it: "Gestione immobiliare",
    },
    "home_page-footer_nav_link_9": {
      en: "Concierge service",
      fr: "Service de conciergerie",
      ru: "Консьерж-сервис",
      it: "Servizio concierge",
    },
    "home_page-footer_nav_link_10": {
      en: "Our commission",
      fr: "Notre Commission",
      ru: "Наша комиссия",
      it: "La nostra commissione",
    },
    "home_page-footer_region_title": {
      en: "Regions",
      fr: "Régions",
      ru: "Регионы",
      it: "Regioni",
    },
    "home_page-footer_region_link_1": {
      en: "Apartments in Beaulieu-sur-Mer",
      fr: "Appartement à Beaulieu-sur-Mer",
      ru: "Апартаменты в Больё-сюр-Мер",
      it: "Appartamenti a Beaulieu-sur-Mer",
    },
    "home_page-footer_region_link_2": {
      en: "Villa in Beaulieu-sur-Mer",
      fr: "Villa à Beaulieu-sur-Mer",
      ru: "Вилла в Больё-сюр-Мер",
      it: "Villa a Beaulieu-sur-Mer",
    },
    "home_page-footer_region_link_3": {
      en: "Villa in Eze",
      fr: "Villa à Eze",
      ru: "Вилла в Эзе",
      it: "Villa a Eze",
    },
    "home_page-footer_region_link_4": {
      en: "Villa in Saint-Jean-Cap-Ferrat",
      fr: "Villa à Saint-Jean-Cap-Ferrat",
      ru: "Вилла в Сен-Жан-Кап-Ферра",
      it: "Villa a Saint-Jean-Cap-Ferrat",
    },
    "home_page-footer_region_link_5": {
      en: "Apartments in Eze",
      fr: "Appartement à Eze",
      ru: "Апартаменты в Эзе",
      it: "Appartamenti a Eze",
    },
    "home_page-footer_region_link_6": {
      en: "Apartments in Saint-Jean-Cap-Ferrat",
      fr: "Appartement à Saint-Jean-Cap-Ferrat",
      ru: "Апартаменты в Сен-Жан-Кап-Ферра",
      it: "Appartamenti a Saint-Jean-Cap-Ferrat",
    },
    "home_page-footer_region_link_policy": {
      en: "Privacy policy",
      fr: "Politique de confidentialité",
      ru: "Политика конфиденциальности",
      it: "Informativa sulla privacy",
    },
  };
  return aboutTexts;
}
