export function homeTexts() {
  const homeTexts = {
    "home_page-title": {
      en: "Azur Life",
      fr: "Azur Life",
      ru: "Azur Life",
      it: "Azur Life",
    },
    "home_page-logo": {
      en: "Azur Life",
      fr: "Azur Life",
      ru: "Azur Life",
      it: "Azur Life",
    },
    "home_page-header_location": {
      en: "France, 46 Boulevard Leclerc, 06310, Beaulieu-sur-Mer",
      fr: "France, 46 Boulevard Leclerc, 06310, Beaulieu-sur-Mer",
      ru: "Франция, бульвар Леклерк, 46, 06310, Болье-сюр-Мер",
      it: "Francia, 46 Boulevard Leclerc, 06310, Beaulieu-sur-Mer",
    },
    "home_page-header_title": {
      en: "Real estate selection with full support in your language",
      fr: "Sélection de biens immobiliers avec un accompagnement complet dans Votre langue",
      ru: "Подбор недвижимости с полным сопровождением на Вашем языке",
      it: "Selezione di immobili con accompagnamento completo nella tua lingua",
    },
    "home_page-header_text": {
      en: "Our agency specializes in premium properties and presents them to you in Russian. The selection of real estate throughout France with a focus on the most privileged and picturesque areas of the French Mediterranean - Nice, Cannes or the Cote d'Azur without unnecessary time and extra charges.",
      fr: "Notre agence est spécialisée dans les objets haut de gamme et vous les présente en russe. Sélection de biens immobiliers dans toute la France en mettant l'accent sur les zones les plus privilégiées et pittoresques de la Méditerranée Française - Nice, Cannes ou la Côte d'Azur sans frais supplémentaires et les frais supplémentaires.",
      ru: "Наше агентство специализируется на премиум объектах и презентует их Вам на русском языке. Подбор недвижимости во всей Франции  с фокусом на самых привилегированных и живописных районах Французского Средиземноморья - Ницца, Канны или Лазурный Берег без лишних временных затрат и наценок.",
      it: "La nostra agenzia è specializzata in strutture premium e li presenta a voi in russo. Selezione di immobili in tutta la Francia con un focus sulle zone più privilegiate e pittoresche del Mediterraneo francese - Nizza, Cannes o la Costa Azzurra senza inutili costi di tempo e costi aggiuntivi.",
    },
    "home_page-header_btn-download": {
      en: "Broshure",
      fr: "Brochure",
      ru: "Скачать презентацию",
      it: "Opuscolo",
    },
    "home_page-header_btn-contact": {
      en: "Contact Us",
      fr: "Contactez-nous",
      ru: "Напишите нам",
      it: "Contattaci",
    },
    "home_page-menu_main_link_1": {
      en: "About us",
      fr: "À propos de nous",
      ru: "О нас",
      it: "Di noi",
    },
    "home_page-menu_main_link_2": {
      en: "All objects",
      fr: "Tous les objets",
      ru: "Все объекты",
      it: "Tutti gli oggetti",
    },
    "home_page-menu_main_link_3": {
      en: "Sale",
      fr: "Vente",
      ru: "Продажа",
      it: "Vendita",
    },
    "home_page-menu_main_link_4": {
      en: "Rent",
      fr: "Location",
      ru: "Аренда",
      it: "Affitto",
    },
    "home_page-menu_main_link_5": {
      en: "Blog",
      fr: "Blog",
      ru: "Блог",
      it: "Blog",
    },
    "home_page-menu_main_link_6": {
      en: "Join us",
      fr: "Rejoignez-nous",
      ru: "Присоединиться к нам",
      it: "Unisciti a noi",
    },
    "home_page-menu_main_link_7": {
      en: "Buy, sell, rent with us",
      fr: "Acheter, vendre, louer avec nous",
      ru: "Купить,  продать, арендовать с нами",
      it: "Comprare, vendere, affittare con noi",
    },
    "home_page-menu_main_link_8": {
      en: "Expert assessment",
      fr: "Avis d'expert",
      ru: "Экспертная оценка",
      it: "Revisione tra pari",
    },
    "home_page-menu_main_link_9": {
      en: "Presentation",
      fr: "Présentation",
      ru: "Презентация",
      it: "Presentazione",
    },
    "home_page-menu_service_link_1": {
      en: "Property Management",
      fr: "Gestion immobilière",
      ru: "Управление недвижимостью",
      it: "Gestione immobiliare",
    },
    "home_page-menu_service_link_2": {
      en: "Concierge service",
      fr: "Service de conciergerie",
      ru: "Консьерж-сервис",
      it: "Servizio concierge",
    },
    "home_page-menu_contact_link": {
      en: "Contact us",
      fr: "Contactez-nous",
      ru: "Связаться с нами",
      it: "Contattaci",
    },
    "home_page-menu_bottom_link_1": {
      en: "Our commission",
      fr: "Notre Commission",
      ru: "Наша комиссия",
      it: "La nostra commissione",
    },
    "home_page-menu_bottom_link_2": {
      en: "Privacy policy",
      fr: "Politique de confidentialité",
      ru: "Политика конфиденциальности",
      it: "Informativa sulla privacy",
    },
    "home_page-popup_form_title": {
      en: "Contact us",
      fr: "Contactez-nous",
      ru: "Связаться с нами",
      it: "Contattaci",
    },
    "home_page-popup_form_text": {
      en: "We are ready to answer any questions about real estate",
      fr: "Nous sommes prêts à répondre aux nouvelles questions sur l'immobilier",
      ru: "Мы готовы ответить на возникающие вопросы о недвижимости",
      it: "Siamo pronti a rispondere alle domande emergenti sul settore immobiliare",
    },
    "home_page-popup_form_name": {
      en: "Name",
      fr: "Nom",
      ru: "Имя",
      it: "Nome",
    },
    "home_page-popup_form_tel": {
      en: "Telephone",
      fr: "Téléphone",
      ru: "Телефон",
      it: "Telefono",
    },
    "home_page-popup_form_email": {
      en: "E-mail",
      fr: "E-mail",
      ru: "Электронная почта",
      it: "E-mail",
    },
    "home_page-popup_form_message": {
      en: "The text of the message",
      fr: "Texte du message",
      ru: "Текст сообщения",
      it: "Testo del messaggio",
    },
    "home_page-popup_form_checkbox": {
      en: "By leaving my email, I accept the privacy policy.",
      fr: "En laissant mon email, j'accepte la politique de confidentialité.",
      ru: "Оставляя свой email, я принимаю политику конфиденциальности.",
      it: "Lasciando la mia email, accetto l'Informativa sulla privacy.",
    },
    "home_page-popup_form_btn": {
      en: "Send a request",
      fr: "Envoyer une demande",
      ru: "Отправить запрос",
      it: "Invia richiesta",
    },
    "home_page-popup_form_location": {
      en: "France, 46 Boulevard Leclerc, 06310, Beaulieu-sur-Mer",
      fr: "France, 46 Boulevard Leclerc, 06310, Beaulieu-sur-Mer",
      ru: "Франция, бульвар Леклерк, 46, 06310, Болье-сюр-Мер",
      it: "Francia, 46 Boulevard Leclerc, 06310, Beaulieu-sur-Mer",
    },
    "home_page-": {
      en: "",
      fr: "",
      ru: "",
      it: "",
    },
    "home_page-": {
      en: "",
      fr: "",
      ru: "",
      it: "",
    },
    "home_page-": {
      en: "",
      fr: "",
      ru: "",
      it: "",
    },
    "home_page-": {
      en: "",
      fr: "",
      ru: "",
      it: "",
    },
    "home_page-": {
      en: "",
      fr: "",
      ru: "",
      it: "",
    },
    "home_page-": {
      en: "",
      fr: "",
      ru: "",
      it: "",
    },
    "home_page-": {
      en: "",
      fr: "",
      ru: "",
      it: "",
    },
    "home_page-": {
      en: "",
      fr: "",
      ru: "",
      it: "",
    },
    "home_page-": {
      en: "",
      fr: "",
      ru: "",
      it: "",
    },
    "home_page-": {
      en: "",
      fr: "",
      ru: "",
      it: "",
    },
    "home_page-foter_form_title": {
      en: "Call me back",
      fr: "Rappelez-moi",
      ru: "Перезвоните мне",
      it: "Richiamami",
    },
    "home_page-foter_form_name": {
      en: "Name",
      fr: "Nom",
      ru: "Имя",
      it: "Nome",
    },
    "home_page-foter_form_tel": {
      en: "Telephone",
      fr: "Téléphone",
      ru: "Телефон",
      it: "Telefono",
    },
    "home_page-foter_form_email": {
      en: "E-mail",
      fr: "E-mail",
      ru: "Электронная почта",
      it: "E-mail",
    },

    "home_page-foter_form_btn": {
      en: "Send a request",
      fr: "Envoyer une demande",
      ru: "Отправить запрос",
      it: "Invia richiesta",
    },
    "home_page-footer_location": {
      en: "France, 46 Boulevard Leclerc, 06310, Beaulieu-sur-Mer",
      fr: "France, 46 Boulevard Leclerc, 06310, Beaulieu-sur-Mer",
      ru: "Франция, бульвар Леклерк, 46, 06310, Болье-сюр-Мер",
      it: "Francia, 46 Boulevard Leclerc, 06310, Beaulieu-sur-Mer",
    },
    "home_page-footer_nav_title": {
      en: "Navigation",
      fr: "Navigation",
      ru: "Навигация",
      it: "Navigazione",
    },
    "home_page-footer_nav_link_1": {
      en: "About us",
      fr: "À propos de nous",
      ru: "О нас",
      it: "Di noi",
    },
    "home_page-footer_nav_link_2": {
      en: "All objects",
      fr: "Tous les objets",
      ru: "Все объекты",
      it: "Tutti gli oggetti",
    },
    "home_page-footer_nav_link_3": {
      en: "Sale",
      fr: "Vente",
      ru: "Продажа",
      it: "Vendita",
    },
    "home_page-footer_nav_link_4": {
      en: "Rent",
      fr: "Location",
      ru: "Аренда",
      it: "Affitto",
    },
    "home_page-footer_nav_link_5": {
      en: "Buy, sell, rent with us",
      fr: "Acheter, vendre, louer avec nous",
      ru: "Купить,  продать, арендовать с нами",
      it: "Comprare, vendere, affittare con noi",
    },
    "home_page-footer_nav_link_6": {
      en: "Presentation",
      fr: "Présentation",
      ru: "Презентация",
      it: "Presentazione",
    },
    "home_page-footer_nav_link_7": {
      en: "Expert assessment",
      fr: "Avis d'expert",
      ru: "Экспертная оценка",
      it: "Revisione tra pari",
    },
    "home_page-footer_nav_link_8": {
      en: "Property Management",
      fr: "Gestion immobilière",
      ru: "Управление недвижимостью",
      it: "Gestione immobiliare",
    },
    "home_page-footer_nav_link_9": {
      en: "Concierge service",
      fr: "Service de conciergerie",
      ru: "Консьерж-сервис",
      it: "Servizio concierge",
    },
    "home_page-footer_nav_link_10": {
      en: "Our commission",
      fr: "Notre Commission",
      ru: "Наша комиссия",
      it: "La nostra commissione",
    },
    "home_page-footer_region_title": {
      en: "Regions",
      fr: "Régions",
      ru: "Регионы",
      it: "Regioni",
    },
    "home_page-footer_region_link_1": {
      en: "Apartments in Beaulieu-sur-Mer",
      fr: "Appartement à Beaulieu-sur-Mer",
      ru: "Апартаменты в Больё-сюр-Мер",
      it: "Appartamenti a Beaulieu-sur-Mer",
    },
    "home_page-footer_region_link_2": {
      en: "Villa in Beaulieu-sur-Mer",
      fr: "Villa à Beaulieu-sur-Mer",
      ru: "Вилла в Больё-сюр-Мер",
      it: "Villa a Beaulieu-sur-Mer",
    },
    "home_page-footer_region_link_3": {
      en: "Villa in Eze",
      fr: "Villa à Eze",
      ru: "Вилла в Эзе",
      it: "Villa a Eze",
    },
    "home_page-footer_region_link_4": {
      en: "Villa in Saint-Jean-Cap-Ferrat",
      fr: "Villa à Saint-Jean-Cap-Ferrat",
      ru: "Вилла в Сен-Жан-Кап-Ферра",
      it: "Villa a Saint-Jean-Cap-Ferrat",
    },
    "home_page-footer_region_link_5": {
      en: "Apartments in Eze",
      fr: "Appartement à Eze",
      ru: "Апартаменты в Эзе",
      it: "Appartamenti a Eze",
    },
    "home_page-footer_region_link_6": {
      en: "Apartments in Saint-Jean-Cap-Ferrat",
      fr: "Appartement à Saint-Jean-Cap-Ferrat",
      ru: "Апартаменты в Сен-Жан-Кап-Ферра",
      it: "Appartamenti a Saint-Jean-Cap-Ferrat",
    },
    "home_page-footer_region_link_policy": {
      en: "Privacy policy",
      fr: "Politique de confidentialité",
      ru: "Политика конфиденциальности",
      it: "Informativa sulla privacy",
    },
  };
  return homeTexts;
}
