export function homeTexts() {
  const homeTexts = {
    "home_page-title": {
      en: "Azur Life",
      fr: "Azur Life",
      ru: "Azur Life",
      it: "Azur Life",
    },
    "home_page-logo": {
      en: "Azur Life",
      fr: "Azur Life",
      ru: "Azur Life",
      it: "Azur Life",
    },
    "home_page-header_location": {
      en: "France, 46 Boulevard Leclerc, 06310, Beaulieu-sur-Mer",
      fr: "France, 46 Boulevard Leclerc, 06310, Beaulieu-sur-Mer",
      ru: "Франция, бульвар Леклерк, 46, 06310, Болье-сюр-Мер",
      it: "Francia, 46 Boulevard Leclerc, 06310, Beaulieu-sur-Mer",
    },
    "home_page-header_title": {
      en: "Real estate selection with full support in your language",
      fr: "Sélection de biens immobiliers avec un accompagnement complet dans Votre langue",
      ru: "Подбор недвижимости с полным сопровождением на Вашем языке",
      it: "Selezione di immobili con accompagnamento completo nella tua lingua",
    },
    "home_page-header_text": {
      en: "Our agency specializes in premium properties and presents them to you in Russian. The selection of real estate throughout France with a focus on the most privileged and picturesque areas of the French Mediterranean - Nice, Cannes or the Cote d'Azur without unnecessary time and extra charges.",
      fr: "Notre agence est spécialisée dans les objets haut de gamme et vous les présente en russe. Sélection de biens immobiliers dans toute la France en mettant l'accent sur les zones les plus privilégiées et pittoresques de la Méditerranée Française - Nice, Cannes ou la Côte d'Azur sans frais supplémentaires et les frais supplémentaires.",
      ru: "Наше агентство специализируется на премиум объектах и презентует их Вам на русском языке. Подбор недвижимости во всей Франции  с фокусом на самых привилегированных и живописных районах Французского Средиземноморья - Ницца, Канны или Лазурный Берег без лишних временных затрат и наценок.",
      it: "La nostra agenzia è specializzata in strutture premium e li presenta a voi in russo. Selezione di immobili in tutta la Francia con un focus sulle zone più privilegiate e pittoresche del Mediterraneo francese - Nizza, Cannes o la Costa Azzurra senza inutili costi di tempo e costi aggiuntivi.",
    },
    "home_page-header_btn-download": {
      en: "Broshure",
      fr: "Brochure",
      ru: "Скачать презентацию",
      it: "Opuscolo",
    },
    "home_page-header_btn-contact": {
      en: "Contact Us",
      fr: "Contactez-nous",
      ru: "Напишите нам",
      it: "Contattaci",
    },
    "home_page-": {
      en: "",
      fr: "",
      ru: "",
      it: "",
    },
    "home_page-": {
      en: "",
      fr: "",
      ru: "",
      it: "",
    },
    "home_page-": {
      en: "",
      fr: "",
      ru: "",
      it: "",
    },
    "home_page-": {
      en: "",
      fr: "",
      ru: "",
      it: "",
    },
    "home_page-": {
      en: "",
      fr: "",
      ru: "",
      it: "",
    },
    "home_page-": {
      en: "",
      fr: "",
      ru: "",
      it: "",
    },
    "home_page-": {
      en: "",
      fr: "",
      ru: "",
      it: "",
    },
    "home_page-": {
      en: "",
      fr: "",
      ru: "",
      it: "",
    },
    "home_page-": {
      en: "",
      fr: "",
      ru: "",
      it: "",
    },
    "home_page-": {
      en: "",
      fr: "",
      ru: "",
      it: "",
    },
    "home_page-": {
      en: "",
      fr: "",
      ru: "",
      it: "",
    },
    "home_page-": {
      en: "",
      fr: "",
      ru: "",
      it: "",
    },
    "home_page-": {
      en: "",
      fr: "",
      ru: "",
      it: "",
    },
    "home_page-": {
      en: "",
      fr: "",
      ru: "",
      it: "",
    },
    "home_page-": {
      en: "",
      fr: "",
      ru: "",
      it: "",
    },
    "home_page-": {
      en: "",
      fr: "",
      ru: "",
      it: "",
    },
    "home_page-": {
      en: "",
      fr: "",
      ru: "",
      it: "",
    },
    "home_page-": {
      en: "",
      fr: "",
      ru: "",
      it: "",
    },
    "home_page-": {
      en: "",
      fr: "",
      ru: "",
      it: "",
    },
    "home_page-": {
      en: "",
      fr: "",
      ru: "",
      it: "",
    },
    "home_page-": {
      en: "",
      fr: "",
      ru: "",
      it: "",
    },
    "home_page-": {
      en: "",
      fr: "",
      ru: "",
      it: "",
    },
    "home_page-": {
      en: "",
      fr: "",
      ru: "",
      it: "",
    },
    "home_page-": {
      en: "",
      fr: "",
      ru: "",
      it: "",
    },
    "home_page-": {
      en: "",
      fr: "",
      ru: "",
      it: "",
    },
    "home_page-foter_form_title": {
      en: "",
      fr: "",
      ru: "Перезвоните мне",
      it: "",
    },
    "home_page-foter_form_name": {
      en: "",
      fr: "",
      ru: "Имя",
      it: "",
    },
    "home_page-foter_form_tel": {
      en: "",
      fr: "",
      ru: "Телефон",
      it: "",
    },
    "home_page-foter_form_email": {
      en: "",
      fr: "",
      ru: "Электронная почта",
      it: "",
    },

    "home_page-foter_form_btn": {
      en: "",
      fr: "",
      ru: "Отправить запрос",
      it: "",
    },
    "home_page-footer_location": {
      en: "France, 46 Boulevard Leclerc, 06310, Beaulieu-sur-Mer",
      fr: "France, 46 Boulevard Leclerc, 06310, Beaulieu-sur-Mer",
      ru: "Франция, бульвар Леклерк, 46, 06310, Болье-сюр-Мер",
      it: "Francia, 46 Boulevard Leclerc, 06310, Beaulieu-sur-Mer",
    },
    "home_page-footer_nav_title": {
      en: "",
      fr: "",
      ru: "Навигация",
      it: "",
    },
    "home_page-footer_nav_link_1": {
      en: "",
      fr: "",
      ru: "О нас ",
      it: "",
    },
    "home_page-footer_nav_link_2": {
      en: "",
      fr: "",
      ru: "Все объекты",
      it: "",
    },
    "home_page-footer_nav_link_3": {
      en: "",
      fr: "",
      ru: "Продажа",
      it: "",
    },
    "home_page-footer_nav_link_4": {
      en: "",
      fr: "",
      ru: "Аренда",
      it: "",
    },
    "home_page-footer_nav_link_5": {
      en: "",
      fr: "",
      ru: "Купить,  продать, арендовать с нами",
      it: "",
    },
    "home_page-footer_nav_link_6": {
      en: "",
      fr: "",
      ru: "Презентация",
      it: "",
    },
    "home_page-footer_nav_link_7": {
      en: "",
      fr: "",
      ru: "Экспертная оценка",
      it: "",
    },
    "home_page-footer_nav_link_8": {
      en: "",
      fr: "",
      ru: "Управление недвижимостью",
      it: "",
    },
    "home_page-footer_nav_link_9": {
      en: "",
      fr: "",
      ru: "Консьерж-сервис",
      it: "",
    },
    "home_page-footer_nav_link_10": {
      en: "",
      fr: "",
      ru: "Наша комиссия",
      it: "",
    },
    "home_page-footer_region_title": {
      en: "",
      fr: "",
      ru: "Регионы",
      it: "",
    },
    "home_page-footer_region_link_1": {
      en: "",
      fr: "",
      ru: "Апартаменты в Больё-сюр-Мер",
      it: "",
    },
    "home_page-footer_region_link_2": {
      en: "",
      fr: "",
      ru: "Вилла в Больё-сюр-Мер",
      it: "",
    },
    "home_page-footer_region_link_3": {
      en: "",
      fr: "",
      ru: "Вилла в Эзе",
      it: "",
    },
    "home_page-footer_region_link_4": {
      en: "",
      fr: "",
      ru: "Вилла в Сен-Жан-Кап-Ферра",
      it: "",
    },
    "home_page-footer_region_link_5": {
      en: "",
      fr: "",
      ru: "Апартаменты в Эзе",
      it: "",
    },
    "home_page-footer_region_link_6": {
      en: "",
      fr: "",
      ru: "Апартаменты в Сен-Жан-Кап-Ферра",
      it: "",
    },
    "home_page-footer_region_link_policy": {
      en: "Privacy policy",
      fr: "Politique de confidentialité",
      ru: "Политика конфиденциальности",
      it: "Informativa sulla privacy",
    },
  };
  return homeTexts;
}
